### ISSUE TITLE
Eventual crash

### ISSUE THREAD

**Issue by Wulf2k** [Wulf2k/DaS-PC-MPChan#63] opened 2016-05-15 07:30 UTC
DustyBoxCube from Reddit:

I get the below exception that causes a crash everytime I run DSCM. It happens after a while of it running in the background (seems pretty random, but usually takes about 20min atleast). Thanks for this awesome tool! I hope the below information helps track down the cause!

See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text ************** System.ArgumentOutOfRangeException: Value of '-1' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'. Parameter name: Value at System.Windows.Forms.NumericUpDown.setValue(Decimal value) at DSCM.DSCM.refTimer_Tick() at DSCM.DSCM._Lambda$_R7-3(Object a0, EventArgs a1) at System.Windows.Forms.Timer.OnTick(EventArgs e) at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m) at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by hydra-chan** [comment] 2016-05-16 02:06
I see this occasionally as well. I suspect it has something to do with that field reading a value from DkS memory that is out of range for that moment. I've hit "Continue" in this situation with no real consequence. It might be safe to ignore.

**Comment by Chronial** [comment] 2016-05-17 15:47
Duplicate of #69

**Closed by Chronial** 2016-05-17 15:47 UTC
