### ISSUE TITLE
Latest Testing, "An item with the same key has already been added"

### ISSUE THREAD

**Issue by Wulf2k** [Wulf2k/DaS-PC-MPChan#44] opened 2016-05-10 02:57 UTC
Reported by atwon23 on Reddit:

This will pop up every 2 to 5 seconds as the dscm-net pool continues to grow. The pool reaches upwards of 800 to 900 players and then error tends to slow down as the pools growth slows.

See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text ************** System.ArgumentException: An item with the same key has already been added. at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary2.Insert(TKey key, TValue value, Boolean add) at System.Collections.Generic.Dictionary2.Add(TKey key, TValue value) at DSCM.DSCM.refMpDataTick() at DSCM.DSCM._Lambda$_2(Object a0, EventArgs a1) at System.Windows.Forms.Timer.OnTick(EventArgs e) at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m) at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies ************** mscorlib Assembly Version: 4.0.0.0 Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

DSCM Assembly Version: 1.0.5973.26548 Win32 Version: 1.0.5973.26548
CodeBase: file:///C:/Users/Toenado/Desktop/ds1%20connect%20tool/testbuild/DSCM-2016-05-09-15.exe

Microsoft.VisualBasic Assembly Version: 10.0.0.0 Win32 Version: 14.6.1038.0 built by: NETFXREL2
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GACMSIL/Microsoft.VisualBasic/v4.0_10.0.0.0_b03f5f7f11d50a3a/Microsoft.VisualBasic.dll

System.Windows.Forms Assembly Version: 4.0.0.0 Win32 Version: 4.6.1038.0 built by: NETFXREL2
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GACMSIL/System.Windows.Forms/v4.0_4.0.0.0_b77a5c561934e089/System.Windows.Forms.dll

System Assembly Version: 4.0.0.0 Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GACMSIL/System/v4.0_4.0.0.0_b77a5c561934e089/System.dll

System.Drawing Assembly Version: 4.0.0.0 Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GACMSIL/System.Drawing/v4.0_4.0.0.0_b03f5f7f11d50a3a/System.Drawing.dll

Accessibility Assembly Version: 4.0.0.0 Win32 Version: 4.6.1038.0 built by: NETFXREL2
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GACMSIL/Accessibility/v4.0_4.0.0.0_b03f5f7f11d50a3a/Accessibility.dll

System.Runtime.Remoting Assembly Version: 4.0.0.0 Win32 Version: 4.6.1038.0 built by: NETFXREL2
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GACMSIL/System.Runtime.Remoting/v4.0_4.0.0.0_b77a5c561934e089/System.Runtime.Remoting.dll

System.Core Assembly Version: 4.0.0.0 Win32 Version: 4.6.1038.0 built by: NETFXREL2
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GACMSIL/System.Core/v4.0_4.0.0.0_b77a5c561934e089/System.Core.dll

System.Configuration Assembly Version: 4.0.0.0 Win32 Version: 4.6.1038.0 built by: NETFXREL2
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GACMSIL/System.Configuration/v4.0_4.0.0.0_b03f5f7f11d50a3a/System.Configuration.dll

System.Xml Assembly Version: 4.0.0.0 Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GACMSIL/System.Xml/v4.0_4.0.0.0_b77a5c561934e089/System.Xml.dll

************** JIT Debugging ************** To enable just-in-time (JIT) debugging, the .config file for this application or computer (machine.config) must have the jitDebugging value set in the system.windows.forms section. The application must also be compiled with debugging enabled.

For example:

<configuration> <system.windows.forms jitDebugging="true" /> </configuration>

When JIT debugging is enabled, any unhandled exception will be sent to the JIT debugger registered on the computer rather than be handled by this dialog box.

**Comment by Chronial** [comment] 2016-05-10 12:21
@Wulf2k I will have a look at this as soon as I find the time.

**Comment by Chronial** [comment] 2016-05-10 13:24
This should be fixed by #47. But not 100% sure, as I can't reproduce it.

**Closed** 2016-05-10 14:01 UTC
