### ISSUE TITLE
Argument out of range

### ISSUE THREAD

**Issue by Wulf2k** [Wulf2k/DaS-PC-MPChan#81] opened 2016-05-19 18:57 UTC
from -Kallor- via /r/darksouls sent 9 hours ago

Sometimes i have this error

System.ArgumentOutOfRangeException: '-1'is not a valid value for 'Value'. 'Value' should be between 'Minimum' e 'Maximum'. Parameter name: Value in System.Windows.Forms.NumericUpDown.setValue(Decimal value) in DSCM.DSCM.refTimer_Tick() in DSCM.DSCM._Lambda$_R7-3(Object a0, EventArgs a1) in System.Windows.Forms.Timer.OnTick(EventArgs e) in System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Chronial** [comment] 2016-05-19 19:54
That is a duplicate of #69 and #66 and already fixed. You just need to do a release ;)

**Comment by Wulf2k** [comment] 2016-05-19 20:01
Excellent work.

Consider your salary doubled!  =]

**Comment by Chronial** [comment] 2016-05-19 20:10
Yay, I'm rich!

Wait, I have a salary? :smiley:

**Comment by Wulf2k** [comment] 2016-05-19 20:23
That's between you and the Human Resources department.

**Closed** 2016-05-20 14:08 UTC
